/* This is the configuration file for the serialunix library. This
 * header file is *private*, it should only be included by the sources
 * of files in this build system, and not be made available outside.
 */

#define NSERIAL_VERSION_MAJOR 1
#define NSERIAL_VERSION_MINOR 1
#define NSERIAL_VERSION_PATCH 4

/* serialoptions.cmake */
#define HAVE_TERMIOS_B0
#define HAVE_TERMIOS_B50
#define HAVE_TERMIOS_B75
#define HAVE_TERMIOS_B110
#define HAVE_TERMIOS_B134
#define HAVE_TERMIOS_B150
#define HAVE_TERMIOS_B200
#define HAVE_TERMIOS_B300
#define HAVE_TERMIOS_B600
#define HAVE_TERMIOS_B1200
#define HAVE_TERMIOS_B1800
#define HAVE_TERMIOS_B2400
#define HAVE_TERMIOS_B4800
#define HAVE_TERMIOS_B9600
#define HAVE_TERMIOS_B19200
#define HAVE_TERMIOS_B38400
#define HAVE_TERMIOS_B57600
/* #undef HAVE_TERMIOS_B76800 */
#define HAVE_TERMIOS_B115200
/* #undef HAVE_TERMIOS_B128000 */
/* #undef HAVE_TERMIOS_B153600 */
#define HAVE_TERMIOS_B230400
/* #undef HAVE_TERMIOS_B256000 */
/* #undef HAVE_TERMIOS_B307200 */
#define HAVE_TERMIOS_B460800
#define HAVE_TERMIOS_B500000
#define HAVE_TERMIOS_B576000
#define HAVE_TERMIOS_B921600
#define HAVE_TERMIOS_B1000000
#define HAVE_TERMIOS_B1152000
#define HAVE_TERMIOS_B1500000
#define HAVE_TERMIOS_B2000000
#define HAVE_TERMIOS_B2500000
#define HAVE_TERMIOS_B3000000
#define HAVE_TERMIOS_B3500000
#define HAVE_TERMIOS_B4000000

#define HAVE_TERMIOS_CMSPAR

#define HAVE_TERMIOS_TIOCGICOUNT
#define HAVE_TERMIOS_TIOCMIWAIT
#define HAVE_LINUX_SERIAL_ICOUNTER_STRUCT
#if defined(HAVE_LINUX_SERIAL_ICOUNTER_STRUCT) && defined(HAVE_TERMIOS_TIOCMIWAIT) && defined(HAVE_TERMIOS_TIOCGICOUNT)
#define HAVE_TIOCMIWAIT
#endif

#define HAVE_TERMIOS_TIOCSBRK
#define HAVE_TERMIOS_TIOCCBRK
#if defined(HAVE_TERMIOS_TIOCSBRK) && defined(HAVE_TERMIOS_TIOCCBRK)
#define HAVE_TERMIOS_BREAK
#endif

#define HAVE_TERMIOS_TIOCINQ
#define HAVE_TERMIOS_FIONREAD
#define HAVE_TERMIOS_TIOCOUTQ
#if !defined(HAVE_TERMIOS_TIOCINQ) && defined(HAVE_TERMIOS_FIONREAD)
#define HAVE_TERMIOS_TIOCINQ
#define TIOCINQ FIONREAD
#endif

#define HAVE_TERMIOS_TIOCNXCL
#define HAVE_TERMIOS_TIOCEXCL
#if defined(HAVE_TERMIOS_TIOCEXCL) && defined(HAVE_TERMIOS_TIOCNXCL)
#define HAVE_TERMIOS_EXCLUSIVE
#endif

